apiVersion: v1
kind: Service
metadata:
  name: student-portal-frontend-service
spec:
  selector:
    app: student-portal-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
